
# Use the correct shell
set -g default-shell $SHELL

# Reset Prefix
set -g prefix C-x
bind C-x send-prefix # C-x C-x will send C-x to terminal

# large history
set-option -g history-limit 10000

# colors
set -g mode-style fg=black
set -g default-terminal "tmux-256color"
set -g pane-active-border-style fg=green

# basic settings
set -g xterm-keys on # for vim
set -g mode-keys vi # vi key
set -g monitor-activity on
set -g window-status-current-style fg=white,reverse

# Automatically set window title
set -g automatic-rename

set -g mouse on
set -g terminal-overrides 'xterm*:smcup@:rmcup@'


# Status Bar
set-option -g status-justify right
set-option -g status-bg black # colour213 # pink
set-option -g status-fg cyan
set-option -g status-interval 5
set-option -g status-left-length 30
set-option -g status-left '#[fg=magenta]» #[fg=cyan,bold]#T#[default]'
set-option -g status-right '#[fg=cyan,bold]#S #[fg=magenta]%R %m-%d#[default]'
set-option -g visual-activity on

# Titles (window number, program name, active (or not)
set-option -g set-titles on
set-option -g set-titles-string '#H:#S.#I.#P #W #T'


# Unbindings
unbind j
unbind C-b # unbind default leader key
unbind '"' # unbind horizontal split
unbind %   # unbind vertical split



# Bindings
# reload tmux conf
bind r source-file ~/.tmux.conf

# new split in current pane (horizontal / vertical)
bind - split-window -v # split pane horizontally
bind | split-window -h # split pane vertically

# list panes
bind-key Space list-panes

bind-key Space command-prompt "joinp -t:%%" # %% = prompt for window.pane [-V|H] # vert|hor split

#previous pane
bind-key -n C-up prev
bind-key -n C-left prev

#next pane
bind-key -n C-right next
bind-key -n C-down next

# Windows
set-window-option -g window-status-current-style bg=red
bind C-j previous-window
bind C-k next-window
bind-key C-a last-window # C-a C-a for last active window
bind A command-prompt "rename-window %%"
setw -g aggressive-resize on

# Navigation
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Resizing
bind-key C-h resize-pane -L
bind-key C-j resize-pane -D
bind-key C-k resize-pane -U
bind-key C-l resize-pane -R

# use vim motion keys while in copy mode
setw -g mode-keys vi

# layouts
bind o select-layout "active-only"
bind M-- select-layout "even-vertical"
bind M-| select-layout "even-horizontal"
bind M-r rotate-window
