---
- name: Setup Development Environment
  hosts: localhost
  become: yes
  vars:
    dotfiles_dir: "{{ ansible_env.PWD }}"

  tasks:
    - name: Ensure Homebrew is installed (macOS)
      shell: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      args:
        executable: /bin/bash
      when: ansible_facts['os_family'] == 'Darwin'

    - name: Ensure required packages are installed (macOS)
      homebrew:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - jq
        - kubectl
        - unzip
        - zip
      when: ansible_facts['os_family'] == 'Darwin'

    - name: Ensure required packages are installed (Linux)
      package:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - jq
        - unzip
        - zip
      when: ansible_facts['os_family'] != 'Darwin'

    - name: Download SDKMAN script
      get_url:
        url: "https://get.sdkman.io"
        dest: "/tmp/sdkman-install.sh"
        mode: '0755'

    - name: Install SDKMAN
      command: "/bin/bash /tmp/sdkman-install.sh"

    - name: Install NVM
      shell: |
        export NVM_DIR="$HOME/.nvm"
        mkdir -p "$NVM_DIR"
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      args:
        executable: /bin/bash

    - name: Clone tmuxifier
      git:
        repo: 'https://github.com/jimeh/tmuxifier.git'
        dest: '{{ ansible_env.HOME }}/.tmuxifier'

    - name: Install tmux-256color terminfo
      shell: |
        tic tmux-256color.terminfo
      args:
        chdir: "{{ dotfiles_dir }}"

    - name: Copy env_setup.sh to home directory
      copy:
        src: "{{ dotfiles_dir }}/env_setup.sh"
        dest: "{{ ansible_env.HOME }}/env_setup.sh"

    - name: Install Pyenv dependencies
      package:
        name: "{{ item }}"
        state: present
      loop:
        - make
        - build-essential
        - libssl-dev
        - zlib1g-dev
        - libbz2-dev
        - libreadline-dev
        - libsqlite3-dev
        - wget
        - curl
        - llvm
        - libncurses5-dev
        - libncursesw5-dev
        - xz-utils
        - tk-dev
        - libffi-dev
        - liblzma-dev
        - python-openssl

    - name: Install Pyenv
      git:
        repo: 'https://github.com/pyenv/pyenv.git'
        dest: '{{ ansible_env.HOME }}/.pyenv'

    - name: Install Golang
      package:
        name: golang
        state: present

    - name: Create symbolic links for Bash
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
        force: yes
      loop:
        - { src: "{{ dotfiles_dir }}/.bashrc", dest: "{{ ansible_env.HOME }}/.bashrc" }
        - { src: "{{ dotfiles_dir }}/.profile", dest: "{{ ansible_env.HOME }}/.profile" }
        - { src: "{{ dotfiles_dir }}/.alias", dest: "{{ ansible_env.HOME }}/.alias" }
        - { src: "{{ dotfiles_dir }}/.alias-aws", dest: "{{ ansible_env.HOME }}/.alias-aws" }
        - { src: "{{ dotfiles_dir }}/.alias-reddit", dest: "{{ ansible_env.HOME }}/.alias-reddit" }
        - { src: "{{ dotfiles_dir }}/.console", dest: "{{ ansible_env.HOME }}/.console" }
        - { src: "{{ dotfiles_dir }}/.tmux.conf", dest: "{{ ansible_env.HOME }}/.tmux.conf" }
      when: zsh_check.rc != 0

    - name: Check if zsh is installed
      shell: |
        if command -v zsh >/dev/null 2>&1; then
          echo "zsh is installed"
        else
          echo "zsh is not installed"
        fi
      register: zsh_installed

    - name: Create symbolic links for Zsh
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
        force: yes
      loop:
        - { src: "{{ dotfiles_dir }}/.zshrc", dest: "{{ ansible_env.HOME }}/.zshrc" }
        - { src: "{{ dotfiles_dir }}/.zprofile", dest: "{{ ansible_env.HOME }}/.zprofile" }
        - { src: "{{ dotfiles_dir }}/.alias", dest: "{{ ansible_env.HOME }}/.alias" }
        - { src: "{{ dotfiles_dir }}/.alias-aws", dest: "{{ ansible_env.HOME }}/.alias-aws" }
        - { src: "{{ dotfiles_dir }}/.alias-reddit", dest: "{{ ansible_env.HOME }}/.alias-reddit" }
        - { src: "{{ dotfiles_dir }}/.console", dest: "{{ ansible_env.HOME }}/.console" }
        - { src: "{{ dotfiles_dir }}/.tmux.conf", dest: "{{ ansible_env.HOME }}/.tmux.conf" }
      when: "'zsh is installed' in zsh_installed.stdout"
